service: sls-sample
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  profile: dev1
  stage: dev
  environment:
    DYNAMODB_TABLE: ${self:service}-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}*'
plugins:
  - serverless-offline
  - serverless-dynamodb-local
custom:
  serverless-offline:
    httpPort: 8083
  dynamodb:
    stages: dev
    start:
      port: 8082
      inMemory: true
      migrate: true
      seed: true
    seed:
      hello:
        sources:
          - table: ${self:provider.environment.DYNAMODB_TABLE}-hello
            sources: [./seeds/hello.json]
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  put:
    handler: handler.put
    environment:
      tableName: ${self:provider.environment.DYNAMODB_TABLE}-hello
    events:
      - http:
          path: messages
          method: post
  get:
    handler: handler.get
    environment:
      tableName: ${self:provider.environment.DYNAMODB_TABLE}-hello
    events:
      - http:
          path: messages/{id}
          method: get
  query:
    handler: handler.query
    environment:
      tableName: ${self:provider.environment.DYNAMODB_TABLE}-hello
    events:
      - http:
          path: messages/query
          method: get
          request:
            parameters:
              querystrings:
                id: true
  getAll:
    handler: handler.getAll
    environment:
      tableName: ${self:provider.environment.DYNAMODB_TABLE}-hello
    events:
      - http:
          path: messages
          method: get
resources:
  Resources:
    Hello:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}-hello
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
